[Loads.Powers]
store_values_type = "all"

[PVSystems.Powers]
store_values_type = "all"

[Circuits.TotalPower]
store_values_type = "all"

[Circuits.LineLosses]
store_values_type = "all"

[Circuits.Losses]
store_values_type = "all"

[Lines.Currents]
store_values_type = "all"

[Lines.Losses]
store_values_type = "all"

[Lines.Powers]
store_values_type = "all"
